project:
  type: website
  output-dir: docs
  
website:
  title: "W. David Walter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.md
      - publications.md
      - projects.md
    tools:
      - icon: envelope
        href: mailto:wdw12@psu
      - icon: twitter
        href: https://twitter.com/walterASEL
      - icon: github
        href: https://github.com/walterASEL
      - icon: linkedin
        href: https://www.linkedin.com/in/w-david-walter-4434a094/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, W. David Walter"

format:
  html:
    theme: darkly
    toc: true

editor: source

